services:
  db:
    container_name: db
    image: postgres:16.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./scripts/multiple_db.sh:/docker-entrypoint-initdb.d/multiple_db.sh
      - ./scripts/init_sql:/docker-entrypoint-initdb.d/init_sql
    env_file:
      - .env
    expose:
      - ${POSTGRES_PORT}
    command: -p ${POSTGRES_PORT}
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  parking:
    container_name: parking-svc
    env_file:
      - .env
    build:
      context: ./
      dockerfile: ./parking/Dockerfile
      args:
        PARKING_REST_PORT: ${PARKING_REST_PORT}
        PARKING_GRPC_PORT: ${PARKING_GRPC_PORT}
        PARKING_HOST: ${PARKING_HOST:-0.0.0.0}
    depends_on:
      db:
        condition: service_healthy
      jaeger:
        condition: service_healthy
    ports:
      - "${PARKING_REST_PORT}:${PARKING_REST_PORT}"
      - "${PARKING_GRPC_PORT}:${PARKING_GRPC_PORT}"
  booking:
    container_name: booking-svc
    env_file:
      - .env
    environment:
      - PORT=${BOOKING_REST_PORT}
      - HOST=${BOOKING_HOST:-0.0.0.0}
    build:
      context: ./
      dockerfile: ./booking/Dockerfile
      args:
        BOOKING_REST_PORT: ${BOOKING_REST_PORT}
        BOOKING_HOST: ${BOOKING_HOST:-0.0.0.0}
    depends_on:
      db:
        condition: service_healthy
      jaeger:
        condition: service_started
      payment:
        condition: service_started
    ports:
      - "${BOOKING_REST_PORT}:${BOOKING_REST_PORT}"
  payment:
    container_name: payment-svc
    env_file:
      - .env
    environment:
      - PORT=${PAYMENT_REST_PORT}
      - HOST=${PAYMENT_HOST:-0.0.0.0}
    build:
      context: ./
      dockerfile: ./payment/Dockerfile
      args:
        PAYMENT_REST_PORT: ${PAYMENT_REST_PORT}
        PAYMENT_GRPC_PORT: ${PAYMENT_GRPC_PORT}
        PAYMENT_HOST: ${PAYMENT_HOST:-0.0.0.0}
    depends_on:
      db:
        condition: service_healthy
      jaeger:
        condition: service_started
    ports:
      - "${PAYMENT_REST_PORT}:${PAYMENT_REST_PORT}"
      - "${PAYMENT_GRPC_PORT}:${PAYMENT_GRPC_PORT}"
  auth:
    container_name: auth-svc
    env_file:
      - .env
    environment:
      - PORT=${AUTH_REST_PORT}
      - HOST=${AUTH_HOST:-0.0.0.0}
    build:
      context: ./
      dockerfile: ./auth/Dockerfile
      args:
        AUTH_REST_PORT: ${AUTH_REST_PORT}
        AUTH_HOST: ${AUTH_HOST:-0.0.0.0}
    depends_on:
      db:
        condition: service_healthy
      keycloak:
        condition: service_healthy
      jaeger:
        condition: service_healthy
    ports:
      - "${AUTH_REST_PORT}:${AUTH_REST_PORT}"
  notification:
    container_name: notification-svc
    build:
      context: ./
      dockerfile: ./notification/Dockerfile
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      - KAFKA_BROKER=${KAFKA_BROKER:-kafka:9092}
      - KAFKA_TOPIC=${KAFKA_TOPIC:-notifications}
      - KAFKA_GROUP_ID=${KAFKA_GROUP_ID:-notification-group}
      - TELEGRAM_API_KEY=${TELEGRAM_API_KEY}
  telegram:
    container_name: telegram
    build:
      context: ./
      dockerfile: ./telegram_bot/Dockerfile
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      keycloak:
        condition: service_healthy
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    expose:
      - ${ZOOKEEPER_PORT}
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_PORT}
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka
    expose:
      - ${KAFKA_PORT}
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:${ZOOKEEPER_PORT}
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:${KAFKA_PORT}
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    tmpfs:
      - /kafka
    healthcheck:
      test: [ "CMD", "kafka-topics", "--list", "--bootstrap-server", "kafka:9092" ]
      interval: 5s
      timeout: 5s
      retries: 10

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: start -Dkeycloak.import=/opt/keycloak/data/import/realm-export.json --db postgres --hostname-strict false --http-enabled true --import-realm
    environment:
      KC_DB_URL: jdbc:postgresql://db:${POSTGRES_PORT}/${AUTH_DB_NAME}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_DB_SCHEMA: public
      KC_FEATURES: preview
      KC_LOG_LEVEL: ERROR
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./keycloak/config/realm-export.json
        target: /opt/keycloak/data/import/realm-export.json
    ports:
      - "${KEYCLOAK_PORT}:${KEYCLOAK_INNER_PORT}"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "/opt/keycloak/bin/kc.sh", "show-config" ]
      start_period: 10s
      interval: 10s
      retries: 5
      timeout: 5s

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    command:
      - "--metrics-backend=prometheus"
      - "--metrics-http-route=/metrics"
    env_file:
      - .env
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - "${JAEGER_AGENT_PORT}:${JAEGER_AGENT_PORT}/udp"
      - "16686:16686"
      - "${JAEGER_SEND_PORT}:${JAEGER_SEND_PORT}"
      - "14250:14250"
    healthcheck:
      test: [ "CMD", "nc", "-z", "jaeger:16686" ]
      start_period: 5s
      interval: 10s
      retries: 5
      timeout: 5s

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    env_file:
      - .env
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "${PROMETHEUS_PORT}:${PROMETHEUS_PORT}"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    env_file:
      - .env
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - GF_INSTALL_PLUGINS=
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - "${GRAFANA_PORT}:${GRAFANA_PORT}"
    depends_on:
      - prometheus

  setup:
    build:
      context: .
      dockerfile: scripts/Dockerfile.setup
    container_name: setup-svc
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - PARKING_DB_NAME=${PARKING_DB_NAME}
      - BOOKING_DB_NAME=${BOOKING_DB_NAME}
      - PAYMENT_DB_NAME=${PAYMENT_DB_NAME}
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KEYCLOAK_CLIENT=${KEYCLOAK_CLIENT}
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - KEYCLOAK_PORT=${KEYCLOAK_PORT}
      - KEYCLOAK_INNER_PORT=${KEYCLOAK_INNER_PORT}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/setup
    depends_on:
      db:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    restart: "no"
    networks:
      - default

volumes:
  postgres_data:
  grafana_data:
